In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

print("Pandas Ver.: " + pd.__version__)
print("Seaborn Ver.: " + sns.__version__)
print("Numpy Ver.: " + np.__version__)

Pandas Ver.: 1.5.3
Seaborn Ver.: 0.12.2
Numpy Ver.: 1.24.2


# Introduction

This is a dataset obtained from Kaggle, and it can be found here: [Steam Store Games (Clean Dataset)](https://www.kaggle.com/datasets/nikdavis/steam-store-games). The data was gathered around May 2019, utilizing the Steam Store and SteamSpy APIs, as stated by the dataset's author on the description.

This is an exploratory analysis of this dataset, mainly utilizing Pandas and its functions. I will try to answer the following questions:

- Top 20 games with the most positive ratings
- Top 20 games with the most negative ratings
- Top 20 games with the highest average playtime
- The most recurring tags/genres
- Publishers with the highest number of games
- Time series of releases (years with the most releases, periods where most games are released in a year etc.)
- What is the correlation between genre and playtime
- What is the correlation between genre and ratings
- What are the most owned games
- What are the least owned games
- Is there a relationship between prices, playtime and reviews, that perhaps points to a sunken cost fallacy?

In [2]:
steam_df = pd.read_csv("./data/steam.csv")
steam_df.head()

appid                       name release_date  english         developer  \
0     10             Counter-Strike   2000-11-01        1             Valve   
1     20      Team Fortress Classic   1999-04-01        1             Valve   
2     30              Day of Defeat   2003-05-01        1             Valve   
3     40         Deathmatch Classic   2001-06-01        1             Valve   
4     50  Half-Life: Opposing Force   1999-11-01        1  Gearbox Software   

  publisher          platforms  required_age  \
0     Valve  windows;mac;linux             0   
1     Valve  windows;mac;linux             0   
2     Valve  windows;mac;linux             0   
3     Valve  windows;mac;linux             0   
4     Valve  windows;mac;linux             0   

                                          categories  genres  \
0  Multi-player;Online Multi-Player;Local Multi-P...  Action   
1  Multi-player;Online Multi-Player;Local Multi-P...  Action   
2              Multi-player;Valve Anti-Cheat enabled  Action   
3  Multi-player;Online Multi-Player;Local Multi-P...  Action   
4  Single-player;Multi-player;Valve Anti-Cheat en...  Action   

                  steamspy_tags  achievements  positive_ratings  \
0        Action;FPS;Multiplayer             0            124534   
1        Action;FPS;Multiplayer             0              3318   
2  FPS;World War II;Multiplayer             0              3416   
3        Action;FPS;Multiplayer             0              1273   
4             FPS;Action;Sci-fi             0              5250   

   negative_ratings  average_playtime  median_playtime             owners  \
0              3339             17612              317  10000000-20000000   
1               633               277               62   5000000-10000000   
2               398               187               34   5000000-10000000   
3               267               258              184   5000000-10000000   
4               288               624              415   5000000-10000000   

   price  
0   7.19  
1   3.99  
2   3.99  
3   3.99  
4   3.99

In [3]:
steam_df.tail()

appid                        name release_date  english  \
27070  1065230             Room of Pandora   2019-04-24        1   
27071  1065570                   Cyber Gun   2019-04-23        1   
27072  1065650            Super Star Blast   2019-04-24        1   
27073  1066700  New Yankee 7: Deer Hunters   2019-04-17        1   
27074  1069460                   Rune Lord   2019-04-24        1   

                developer             publisher    platforms  required_age  \
27070         SHEN JIAWEI           SHEN JIAWEI      windows             0   
27071      Semyon Maximov      BekkerDev Studio      windows             0   
27072         EntwicklerX           EntwicklerX      windows             0   
27073  Yustas Game Studio  Alawar Entertainment  windows;mac             0   
27074    Adept Studios GD  Alawar Entertainment  windows;mac             0   

                                              categories  \
27070                   Single-player;Steam Achievements   
27071                                      Single-player   
27072  Single-player;Multi-player;Co-op;Shared/Split ...   
27073                          Single-player;Steam Cloud   
27074                          Single-player;Steam Cloud   

                       genres           steamspy_tags  achievements  \
27070  Adventure;Casual;Indie  Adventure;Indie;Casual             7   
27071  Action;Adventure;Indie  Action;Indie;Adventure             0   
27072     Action;Casual;Indie     Action;Indie;Casual            24   
27073  Adventure;Casual;Indie  Indie;Casual;Adventure             0   
27074  Adventure;Casual;Indie  Indie;Casual;Adventure             0   

       positive_ratings  negative_ratings  average_playtime  median_playtime  \
27070                 3                 0                 0                0   
27071                 8                 1                 0                0   
27072                 0                 1                 0                0   
27073                 2                 0                 0                0   
27074                 4                 0                 0                0   

        owners  price  
27070  0-20000   2.09  
27071  0-20000   1.69  
27072  0-20000   3.99  
27073  0-20000   5.19  
27074  0-20000   5.19

Getting a summary of the statistics in my dataset

In [4]:
steam_df.describe()

appid       english  required_age  achievements  \
count  2.707500e+04  27075.000000  27075.000000  27075.000000   
mean   5.962035e+05      0.981127      0.354903     45.248864   
std    2.508942e+05      0.136081      2.406044    352.670281   
min    1.000000e+01      0.000000      0.000000      0.000000   
25%    4.012300e+05      1.000000      0.000000      0.000000   
50%    5.990700e+05      1.000000      0.000000      7.000000   
75%    7.987600e+05      1.000000      0.000000     23.000000   
max    1.069460e+06      1.000000     18.000000   9821.000000   

       positive_ratings  negative_ratings  average_playtime  median_playtime  \
count      2.707500e+04      27075.000000      27075.000000      27075.00000   
mean       1.000559e+03        211.027147        149.804949        146.05603   
std        1.898872e+04       4284.938531       1827.038141       2353.88008   
min        0.000000e+00          0.000000          0.000000          0.00000   
25%        6.000000e+00          2.000000          0.000000          0.00000   
50%        2.400000e+01          9.000000          0.000000          0.00000   
75%        1.260000e+02         42.000000          0.000000          0.00000   
max        2.644404e+06     487076.000000     190625.000000     190625.00000   

              price  
count  27075.000000  
mean       6.078193  
std        7.874922  
min        0.000000  
25%        1.690000  
50%        3.990000  
75%        7.190000  
max      421.990000

In [5]:
steam_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27075 entries, 0 to 27074
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   appid             27075 non-null  int64  
 1   name              27075 non-null  object 
 2   release_date      27075 non-null  object 
 3   english           27075 non-null  int64  
 4   developer         27075 non-null  object 
 5   publisher         27075 non-null  object 
 6   platforms         27075 non-null  object 
 7   required_age      27075 non-null  int64  
 8   categories        27075 non-null  object 
 9   genres            27075 non-null  object 
 10  steamspy_tags     27075 non-null  object 
 11  achievements      27075 non-null  int64  
 12  positive_ratings  27075 non-null  int64  
 13  negative_ratings  27075 non-null  int64  
 14  average_playtime  27075 non-null  int64  
 15  median_playtime   27075 non-null  int64  
 16  owners            27075 non-null  object

Verifying how many lines and columns my dataset has

In [6]:
print(steam_df.shape)

(27075, 18)


Checking if there are any null values in my dataframe. This is good practice, although this dataset was already cleaned by the author.

In [7]:
print(steam_df.isnull().sum())

appid               0
name                0
release_date        0
english             0
developer           0
publisher           0
platforms           0
required_age        0
categories          0
genres              0
steamspy_tags       0
achievements        0
positive_ratings    0
negative_ratings    0
average_playtime    0
median_playtime     0
owners              0
price               0
dtype: int64


Columns appid and steamspy_tags will be dropped. The former because it doesn't have any relevant information for this exploratory analysis, and the latter because it has very similar data to the genres column, and that is the chosen column to be used in this analysis.

In [8]:
steam_df = steam_df.drop(["appid", "steamspy_tags"], axis=1)
steam_df.head()

name release_date  english         developer  \
0             Counter-Strike   2000-11-01        1             Valve   
1      Team Fortress Classic   1999-04-01        1             Valve   
2              Day of Defeat   2003-05-01        1             Valve   
3         Deathmatch Classic   2001-06-01        1             Valve   
4  Half-Life: Opposing Force   1999-11-01        1  Gearbox Software   

  publisher          platforms  required_age  \
0     Valve  windows;mac;linux             0   
1     Valve  windows;mac;linux             0   
2     Valve  windows;mac;linux             0   
3     Valve  windows;mac;linux             0   
4     Valve  windows;mac;linux             0   

                                          categories  genres  achievements  \
0  Multi-player;Online Multi-Player;Local Multi-P...  Action             0   
1  Multi-player;Online Multi-Player;Local Multi-P...  Action             0   
2              Multi-player;Valve Anti-Cheat enabled  Action             0   
3  Multi-player;Online Multi-Player;Local Multi-P...  Action             0   
4  Single-player;Multi-player;Valve Anti-Cheat en...  Action             0   

   positive_ratings  negative_ratings  average_playtime  median_playtime  \
0            124534              3339             17612              317   
1              3318               633               277               62   
2              3416               398               187               34   
3              1273               267               258              184   
4              5250               288               624              415   

              owners  price  
0  10000000-20000000   7.19  
1   5000000-10000000   3.99  
2   5000000-10000000   3.99  
3   5000000-10000000   3.99  
4   5000000-10000000   3.99

Altering the genres column inplace. Since this column has many genres separated by semicolons, we will disregard the ones that come after the first and consider that the main genre.

In [9]:
split_genres = steam_df["genres"].str.split(";", n=1, expand=True)
steam_df["genres"] = split_genres[0]
steam_df.head()

name release_date  english         developer  \
0             Counter-Strike   2000-11-01        1             Valve   
1      Team Fortress Classic   1999-04-01        1             Valve   
2              Day of Defeat   2003-05-01        1             Valve   
3         Deathmatch Classic   2001-06-01        1             Valve   
4  Half-Life: Opposing Force   1999-11-01        1  Gearbox Software   

  publisher          platforms  required_age  \
0     Valve  windows;mac;linux             0   
1     Valve  windows;mac;linux             0   
2     Valve  windows;mac;linux             0   
3     Valve  windows;mac;linux             0   
4     Valve  windows;mac;linux             0   

                                          categories  genres  achievements  \
0  Multi-player;Online Multi-Player;Local Multi-P...  Action             0   
1  Multi-player;Online Multi-Player;Local Multi-P...  Action             0   
2              Multi-player;Valve Anti-Cheat enabled  Action             0   
3  Multi-player;Online Multi-Player;Local Multi-P...  Action             0   
4  Single-player;Multi-player;Valve Anti-Cheat en...  Action             0   

   positive_ratings  negative_ratings  average_playtime  median_playtime  \
0            124534              3339             17612              317   
1              3318               633               277               62   
2              3416               398               187               34   
3              1273               267               258              184   
4              5250               288               624              415   

              owners  price  
0  10000000-20000000   7.19  
1   5000000-10000000   3.99  
2   5000000-10000000   3.99  
3   5000000-10000000   3.99  
4   5000000-10000000   3.99

There's a lot of zeroes in the column required_age, so a query is run to check whether that is the situation for the entire column or not, in case it's bad data

In [10]:
steam_df.query("required_age > 0")

name release_date  \
46                                              Quake IV   2011-08-04   
132                   Company of Heroes - Legacy Edition   2007-07-17   
133    Warhammer® 40,000: Dawn of War® - Game of the ...   2007-08-07   
134       Warhammer® 40,000: Dawn of War® - Dark Crusade   2007-08-07   
136                          Condemned: Criminal Origins   2012-10-29   
...                                                  ...          ...   
26707                                               Faux   2019-03-18   
26728                                       Roach Killer   2019-04-15   
26732                                     oscar and paul   2019-03-15   
26983                        Adecke - Cards Games Deluxe   2019-04-20   
27033                                         Candy Girl   2019-04-11   

       english                             developer  \
46           1               RavenSoft / id Software   
132          1                   Relic Entertainment   
133          1                   Relic Entertainment   
134          1                   Relic Entertainment   
136          1                              Monolith   
...        ...                                   ...   
26707        1                             Pelagames   
26728        1  Highlight Visual Effects Development   
26732        1       NGS GAMES STUDIO;PIXEL ART GAME   
26983        1                      Philippe Pelchat   
27033        1                        hallunazigames   

                                  publisher          platforms  required_age  \
46                       Bethesda Softworks            windows            18   
132                                    SEGA            windows            18   
133                                    SEGA            windows            16   
134                                    SEGA            windows            16   
136                                    SEGA            windows            18   
...                                     ...                ...           ...   
26707                             Pelagames            windows            12   
26728  Highlight Visual Effects Development            windows            16   
26732                      NGS GAMES STUDIO            windows            12   
26983                      Philippe Pelchat  windows;mac;linux            12   
27033                        hallunazigames            windows            16   

                                              categories    genres  \
46                Single-player;Multi-player;Steam Cloud    Action   
132    Single-player;Multi-player;Steam Trading Cards...   Violent   
133    Single-player;Multi-player;Steam Trading Cards...  Strategy   
134               Single-player;Multi-player;Steam Cloud  Strategy   
136                                        Single-player    Action   
...                                                  ...       ...   
26707  Single-player;Steam Achievements;Partial Contr...    Action   
26728  Single-player;Steam Achievements;Steam Leaderb...    Action   
26732                                      Single-player    Action   
26983                                      Single-player    Casual   
27033                                      Single-player    Casual   

       achievements  positive_ratings  negative_ratings  average_playtime  \
46                0               891               171                36   
132               0              4772               320               175   
133               0              3485               206               309   
134               0              2849               133               543   
136               0              1243               221               312   
...             ...               ...               ...               ...   
26707            10                 3                 1                 0   
26728             1                 1                 2                 0   
26732  

Discovering the top 20 games with the most positive reviews on Steam. First, the 20 largest values in the positive_ratings column will be filtered.

In [11]:
steam_df['positive_ratings'].nlargest(n=20)

25       2644404
22        863507
19        515879
12836     496184
121       363721
2478      329061
1467      308657
3362      292574
1120      255600
21        251789
5235      251178
2031      242561
1025      237303
1634      226541
2016      220370
2964      202930
1596      176769
8129      169580
4712      145035
903       144595
Name: positive_ratings, dtype: int64

Then, a query is applied to select only those games whose quantity of positive ratings is above the last number retrieved in the filter. In this case, that would be 144595.

In [12]:
steam_df.query("positive_ratings >= 144595").sort_values(by="positive_ratings", ascending=False)

name release_date  english  \
25     Counter-Strike: Global Offensive   2012-08-21        1   
22                               Dota 2   2013-07-09        1   
19                      Team Fortress 2   2007-10-10        1   
12836     PLAYERUNKNOWN'S BATTLEGROUNDS   2017-12-21        1   
121                         Garry's Mod   2006-11-29        1   
2478                 Grand Theft Auto V   2015-04-13        1   
1467                           PAYDAY 2   2013-08-13        1   
3362                           Unturned   2017-07-07        1   
1120                           Terraria   2011-05-16        1   
21                        Left 4 Dead 2   2009-11-19        1   
5235    Tom Clancy's Rainbow Six® Siege   2015-12-01        1   
2031                     Rocket League®   2015-07-07        1   
1025        The Elder Scrolls V: Skyrim   2011-11-10        1   
1634                           Warframe   2013-03-25        1   
2016                               Rust   2018-02-08        1   
2964          The Witcher® 3: Wild Hunt   2015-05-18        1   
1596             Euro Truck Simulator 2   2012-10-12        1   
8129                          Paladins®   2018-05-08        1   
4712              ARK: Survival Evolved   2017-08-27        1   
903                       Borderlands 2   2012-09-20        1   

                                               developer  \
25                       Valve;Hidden Path Entertainment   
22                                                 Valve   
19                                                 Valve   
12836                                   PUBG Corporation   
121                                    Facepunch Studios   
2478                                      Rockstar North   
1467                     OVERKILL - a Starbreeze Studio.   
3362                               Smartly Dressed Games   
1120                                            Re-Logic   
21                                                 Valve   
5235                                    Ubisoft Montreal   
2031                                       Psyonix, Inc.   
1025                               Bethesda Game Studios   
1634                                    Digital Extremes   
2016                                   Facepunch Studios   
2964                                      CD PROJEKT RED   
1596                                        SCS Software   
8129                                     Evil Mojo Games   
4712   Studio Wildcard;Instinct Games;Efecto Studios;...   
903           Gearbox Software;Aspyr (Mac);Aspyr (Linux)   

                          publisher          platforms  required_age  \
25                            Valve  windows;mac;linux             0   
22                            Valve  windows;mac;linux             0   
19                            Valve  windows;mac;linux             0   
12836              PUBG Corporation            windows             0   
121                           Valve  windows;mac;linux             0   
2478                 Rockstar Games            windows            18   
1467       Starbreeze Publishing AB      windows;linux            18   
3362          Smartly Dressed Games  windows;mac;linux             0   
1120                       Re-Logic  windows;mac;linux             0   
21                            Valve  windows;mac;linux             0   
5235                        Ubisoft            windows             0   
2031                  Psyonix, Inc.  windows;mac;linux             0   
1025             Bethesda Softworks            windows            16   
1634               Digital Extremes            windows            16   
2016              Facepunch Studios        windows;mac            18   
2964                 CD PROJEKT RED            windows             0   
1596                   SCS Software  windows;mac;linux             0   
8129                 Hi-Rez Studios            windows             0   
4712                Studio Wildcard  win

Unsurprisingly, the podium is occupied by the wildly popular PC games Counter-Strike: Global Offensive, Dota 2 and Team Fortress 2, all three developed by Steam's own parent company, Valve Software.

Now, going to the opposite end, discovering the top 20 games with the most negative reviews on Steam. Filtering for the the 20 largest values in the negative_ratings column.

In [13]:
steam_df["negative_ratings"].nlargest(20)

12836    487076
25       402313
22       142079
2478     139308
7809      91664
1506      77169
4712      66603
5235      59620
1467      56523
2563      56488
2016      53709
5916      45377
6046      44985
12965     35294
1607      34416
19        34036
8129      32407
3362      31482
3251      30987
3347      25920
Name: negative_ratings, dtype: int64

Applying a query to select only those games whose quantity of negative ratings is above the last number retrieved in the filter, 25920.

In [14]:
steam_df.query("negative_ratings >= 25920").sort_values(by="negative_ratings", ascending=False)

name release_date  english  \
12836     PLAYERUNKNOWN'S BATTLEGROUNDS   2017-12-21        1   
25     Counter-Strike: Global Offensive   2012-08-21        1   
22                               Dota 2   2013-07-09        1   
2478                 Grand Theft Auto V   2015-04-13        1   
7809                   Z1 Battle Royale   2018-02-28        1   
1506                               DayZ   2018-12-13        1   
4712              ARK: Survival Evolved   2017-08-27        1   
5235    Tom Clancy's Rainbow Six® Siege   2015-12-01        1   
1467                           PAYDAY 2   2013-08-13        1   
2563                       No Man's Sky   2016-08-12        1   
2016                               Rust   2018-02-08        1   
5916                          Fallout 4   2015-11-09        1   
6046                   Dead by Daylight   2016-06-14        1   
12965             MONSTER HUNTER: WORLD   2018-08-09        1   
1607                  Heroes & Generals   2016-10-18        1   
19                      Team Fortress 2   2007-10-10        1   
8129                          Paladins®   2018-05-08        1   
3362                           Unturned   2017-07-07        1   
3251                          Robocraft   2017-08-24        1   
3347                         FOR HONOR™   2017-02-13        1   

                                               developer  \
12836                                   PUBG Corporation   
25                       Valve;Hidden Path Entertainment   
22                                                 Valve   
2478                                      Rockstar North   
7809                                               NantG   
1506                                 Bohemia Interactive   
4712   Studio Wildcard;Instinct Games;Efecto Studios;...   
5235                                    Ubisoft Montreal   
1467                     OVERKILL - a Starbreeze Studio.   
2563                                         Hello Games   
2016                                   Facepunch Studios   
5916                               Bethesda Game Studios   
6046                              Behaviour Digital Inc.   
12965                                   CAPCOM Co., Ltd.   
1607                                           RETO MOTO   
19                                                 Valve   
8129                                     Evil Mojo Games   
3362                               Smartly Dressed Games   
3251                                             Freejam   
3347   Ubisoft Montreal;Ubisoft Quebec;Ubisoft Toront...   

                      publisher          platforms  required_age  \
12836          PUBG Corporation            windows             0   
25                        Valve  windows;mac;linux             0   
22                        Valve  windows;mac;linux             0   
2478             Rockstar Games            windows            18   
7809      Daybreak Game Company            windows             0   
1506        Bohemia Interactive            windows            18   
4712            Studio Wildcard  windows;mac;linux             0   
5235                    Ubisoft            windows             0   
1467   Starbreeze Publishing AB      windows;linux            18   
2563                Hello Games            windows             0   
2016          Facepunch Studios        windows;mac            18   
5916         Bethesda Softworks            windows            18   
6046     Behaviour Digital Inc.            windows             0   
12965          CAPCOM Co., Ltd.            windows             0   
1607                  RETO MOTO            windows             0   
19                        Valve  windows;mac;linux             0   
8129             Hi-Rez Studios            windows             0   
3362      Smartly Dressed Games  windows;mac;linux             0   
3251                    Freejam  windows;mac;linux             0   
3347                    Ubisoft            windo

Popular video games, especially those with live-service and multiplayer components, can often be very divisive or controversial due to the fickle nature of the player bases and the state of their satisfaction or dissatisfaction with the games as they get updated and changed. Thus Counter-Strike: Global Offensive and Dota 2 occupy 2 of the 3 spots of games with the most negative reviews.